using System.Collections.Concurrent;
using System.Text;
using System.Text.RegularExpressions;
using ClaudeManager.Hub.Persistence.Entities;
using Renci.SshNet;

namespace ClaudeManager.Hub.Services;

/// <summary>
/// Manages a per-host nginx Docker container that reverse-proxies vLLM instances.
/// One upstream block is generated per distinct model ID; instances of the same model
/// are load-balanced within that upstream.
/// </summary>
public class NginxProxyService(ILogger<NginxProxyService> logger)
{
    private readonly ConcurrentDictionary<string, (NginxProxyStatus Status, string? Error, DateTimeOffset UpdatedAt)>
        _statusCache = new();

    private const string ContainerName = "vllm-nginx-proxy";
    private const string RemoteConfigDir = "~/.vllm-proxy";
    private const string RemoteConfigPath = "~/.vllm-proxy/nginx.conf";

    // ── Config generation ─────────────────────────────────────────────────────

    /// <summary>
    /// Generates a complete nginx.conf for the given set of running deployments.
    /// Uses per-model upstreams with path-prefix routing.
    /// </summary>
    internal static string GenerateConfig(IReadOnlyList<LlmDeploymentEntity> runningDeployments, int proxyPort)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by Claude Manager — {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("# Do not edit manually — changes will be overwritten on deployment changes.");
        sb.AppendLine();
        sb.AppendLine("events {");
        sb.AppendLine("    worker_connections 1024;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("http {");
        sb.AppendLine("    include /etc/nginx/mime.types;");
        sb.AppendLine("    default_type application/octet-stream;");
        sb.AppendLine("    sendfile on;");
        sb.AppendLine("    keepalive_timeout 65;");
        sb.AppendLine();

        var byModel = runningDeployments
            .GroupBy(d => d.ModelId)
            .OrderBy(g => g.Key)
            .ToList();

        if (byModel.Count == 0)
        {
            // No running instances — return 503 for all requests
            sb.AppendLine($"    server {{");
            sb.AppendLine($"        listen {proxyPort};");
            sb.AppendLine($"        return 503 \"No vLLM instances are currently running.\";");
            sb.AppendLine($"    }}");
        }
        else
        {
            // Upstream block per model
            foreach (var group in byModel)
            {
                var upstreamName = ModelToUpstreamName(group.Key);
                sb.AppendLine($"    upstream {upstreamName} {{");
                foreach (var d in group.OrderBy(x => x.HostPort))
                    sb.AppendLine($"        server 127.0.0.1:{d.HostPort};");
                sb.AppendLine($"        keepalive 32;");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }

            // Server block with per-model location routing
            sb.AppendLine($"    server {{");
            sb.AppendLine($"        listen {proxyPort};");
            sb.AppendLine($"        client_max_body_size 0;");
            sb.AppendLine();

            foreach (var group in byModel)
            {
                var upstreamName = ModelToUpstreamName(group.Key);
                var pathSlug     = ModelToPathSlug(group.Key);
                sb.AppendLine($"        # {group.Key}");
                sb.AppendLine($"        location /{pathSlug}/ {{");
                sb.AppendLine($"            proxy_pass http://{upstreamName}/;");
                sb.AppendLine($"            proxy_http_version 1.1;");
                sb.AppendLine($"            proxy_set_header Connection \"\";");
                sb.AppendLine($"            proxy_set_header Host $host;");
                sb.AppendLine($"            proxy_read_timeout 300s;");
                sb.AppendLine($"            proxy_connect_timeout 10s;");
                sb.AppendLine($"        }}");
                sb.AppendLine();
            }

            sb.AppendLine($"    }}");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Converts a HuggingFace model ID to a valid nginx upstream identifier.
    /// e.g. "meta-llama/Llama-3.1-8B-Instruct" → "vllm_meta_llama_llama_3_1_8b_instruct"
    /// </summary>
    internal static string ModelToUpstreamName(string modelId)
    {
        var slug = Regex.Replace(modelId.ToLowerInvariant(), @"[^a-z0-9]+", "_").Trim('_');
        return "vllm_" + slug;
    }

    /// <summary>
    /// Converts a HuggingFace model ID to a URL-safe path prefix.
    /// e.g. "meta-llama/Llama-3.1-8B-Instruct" → "meta-llama-llama-3.1-8b-instruct"
    /// </summary>
    internal static string ModelToPathSlug(string modelId)
    {
        // Keep dots (valid in URLs), replace everything else non-alphanumeric with dashes
        var slug = Regex.Replace(modelId.ToLowerInvariant(), @"[^a-z0-9.\-]+", "-").Trim('-');
        return Regex.Replace(slug, @"-{2,}", "-");
    }

    // ── Remote operations ─────────────────────────────────────────────────────

    /// <summary>
    /// Writes the generated nginx config to the host and starts or reloads the proxy container.
    /// Returns null on success, or an error message on failure.
    /// </summary>
    public async Task<string?> ApplyConfigAsync(
        GpuHostEntity host,
        IReadOnlyList<LlmDeploymentEntity> runningDeployments,
        CancellationToken ct = default)
    {
        if (host.ProxyPort is null)
            return "No proxy port configured for this host.";

        var config      = GenerateConfig(runningDeployments, host.ProxyPort.Value);
        var configB64   = Convert.ToBase64String(Encoding.UTF8.GetBytes(config));

        // One compound shell command: write config then start/reload container
        var cmd = BuildApplyCommand(configB64);

        logger.LogInformation("Applying nginx proxy config on {Host} (port {Port}, {Count} deployments)",
            host.Host, host.ProxyPort, runningDeployments.Count);

        var (_, stderr, exitCode) = await ExecAsync(host, cmd, ct);

        if (exitCode != 0)
        {
            var error = stderr?.Trim() ?? "nginx apply command failed with no output.";
            logger.LogWarning("Nginx apply failed on {Host}: {Error}", host.Host, error);
            SetCache(host.HostId, NginxProxyStatus.Error, error);
            return error;
        }

        SetCache(host.HostId, NginxProxyStatus.Running, null);
        return null;
    }

    /// <summary>
    /// Queries the live status of the nginx proxy container on the host.
    /// </summary>
    public async Task<NginxProxyStatus> GetStatusAsync(
        GpuHostEntity host, CancellationToken ct = default)
    {
        var cmd = $"docker inspect -f '{{{{.State.Status}}}}' {ContainerName} 2>/dev/null || echo not_found";
        var (stdout, _, _) = await ExecAsync(host, cmd, ct);
        var status = ParseContainerStatus(stdout?.Trim());
        SetCache(host.HostId, status, null);
        return status;
    }

    /// <summary>
    /// Returns the nginx config file currently deployed on the host.
    /// </summary>
    public async Task<(string? Config, string? Error)> GetCurrentConfigAsync(
        GpuHostEntity host, CancellationToken ct = default)
    {
        var cmd = $"cat {RemoteConfigPath} 2>/dev/null";
        var (stdout, stderr, exitCode) = await ExecAsync(host, cmd, ct);

        if (exitCode != 0 && !string.IsNullOrWhiteSpace(stderr))
            return (null, stderr.Trim());

        return (stdout ?? "", null);
    }

    /// <summary>
    /// Returns the cached status for a host without making a remote call.
    /// </summary>
    public (NginxProxyStatus Status, string? Error, DateTimeOffset UpdatedAt) GetCachedStatus(string hostId) =>
        _statusCache.TryGetValue(hostId, out var entry)
            ? entry
            : (NginxProxyStatus.Unknown, null, DateTimeOffset.MinValue);

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string BuildApplyCommand(string configBase64)
    {
        // Write config file, then start or reload the container — all in one SSH round-trip.
        // We mount the file as /etc/nginx/nginx.conf to replace the default entirely.
        var sb = new StringBuilder();
        sb.Append($"mkdir -p {RemoteConfigDir}");
        sb.Append($" && echo {configBase64} | base64 -d > {RemoteConfigPath}");
        sb.Append($" && if docker inspect {ContainerName} > /dev/null 2>&1; then");
        sb.Append($"     if [ \"$(docker inspect -f '{{{{.State.Status}}}}' {ContainerName})\" = \"running\" ]; then");
        sb.Append($"         docker exec {ContainerName} nginx -s reload;");
        sb.Append($"     else");
        sb.Append($"         docker start {ContainerName};");
        sb.Append($"     fi;");
        sb.Append($" else");
        sb.Append($"     docker run -d --name {ContainerName} --network host --restart unless-stopped");
        sb.Append($"         -v \"$HOME/.vllm-proxy/nginx.conf:/etc/nginx/nginx.conf:ro\"");
        sb.Append($"         nginx:alpine;");
        sb.Append($" fi");
        return sb.ToString();
    }

    private static NginxProxyStatus ParseContainerStatus(string? raw) => raw switch
    {
        "running"                           => NginxProxyStatus.Running,
        "exited" or "created" or "paused"   => NginxProxyStatus.Stopped,
        "not_found" or null or ""           => NginxProxyStatus.NotFound,
        _                                   => NginxProxyStatus.Unknown,
    };

    private void SetCache(string hostId, NginxProxyStatus status, string? error) =>
        _statusCache[hostId] = (status, error, DateTimeOffset.UtcNow);

    private async Task<(string? Stdout, string? Stderr, int ExitCode)> ExecAsync(
        GpuHostEntity host, string command, CancellationToken ct)
    {
        if (IsLocalHost(host.Host))
            return await ExecLocalAsync(command, ct);

        var auth = BuildAuth(host);
        if (auth is null)
            return (null, "No SSH authentication configured (SshKeyPath or SshPassword required).", 1);

        try
        {
            var connInfo = new Renci.SshNet.ConnectionInfo(host.Host, host.SshPort, host.SshUser!, auth);
            using var client = new SshClient(connInfo);
            await Task.Run(() => client.Connect(), ct);
            using var cmd = client.RunCommand(command);
            client.Disconnect();
            return (cmd.Result, cmd.Error, cmd.ExitStatus ?? 0);
        }
        catch (OperationCanceledException)
        {
            return (null, "Operation cancelled.", 1);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "SSH command failed on {Host}", host.Host);
            return (null, ex.Message, 1);
        }
    }

    private static async Task<(string? Stdout, string? Stderr, int ExitCode)> ExecLocalAsync(
        string command, CancellationToken ct)
    {
        try
        {
            var psi = OperatingSystem.IsWindows()
                ? new System.Diagnostics.ProcessStartInfo("cmd.exe", $"/C {command}")
                : new System.Diagnostics.ProcessStartInfo("bash", $"-c \"{command.Replace("\"", "\\\"")}\"");

            psi.UseShellExecute        = false;
            psi.RedirectStandardOutput = true;
            psi.RedirectStandardError  = true;
            psi.CreateNoWindow         = true;

            using var proc = System.Diagnostics.Process.Start(psi)!;
            var stdout = await proc.StandardOutput.ReadToEndAsync(ct);
            var stderr = await proc.StandardError.ReadToEndAsync(ct);
            await proc.WaitForExitAsync(ct);
            return (stdout, stderr, proc.ExitCode);
        }
        catch (OperationCanceledException)
        {
            return (null, "Operation cancelled.", 1);
        }
        catch (Exception ex)
        {
            return (null, ex.Message, 1);
        }
    }

    private static bool IsLocalHost(string host) =>
        host is "localhost" or "127.0.0.1" or "::1";

    private static AuthenticationMethod? BuildAuth(GpuHostEntity host)
    {
        if (host.SshKeyPath is not null)
        {
            var path = host.SshKeyPath.Replace("~",
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile));
            return new PrivateKeyAuthenticationMethod(host.SshUser, new PrivateKeyFile(path));
        }
        if (host.SshPassword is not null)
            return new PasswordAuthenticationMethod(host.SshUser, host.SshPassword);
        return null;
    }
}
