using System.Collections.Concurrent;
using System.Text;
using ClaudeManager.Hub.Persistence.Entities;
using ClaudeManager.Hub.Services.Docker;

namespace ClaudeManager.Hub.Services;

/// <summary>
/// Manages a per-host nginx Docker container that reverse-proxies LLM instances (vLLM or llama.cpp).
/// One upstream block is generated per distinct model ID; instances of the same model
/// are load-balanced within that upstream.
/// </summary>
public class NginxProxyService(ILogger<NginxProxyService> logger, IDockerExecutor executor)
{
    private readonly ConcurrentDictionary<string, (NginxProxyStatus Status, string? Error, DateTimeOffset UpdatedAt)>
        _statusCache = new();

    private const string ContainerName  = "llm-nginx-proxy";
    private const string ConfigSubDir   = ".llm-proxy";
    private const string ConfigFile     = "nginx.conf";

    // ── Config generation ─────────────────────────────────────────────────────

    /// <summary>
    /// Generates a complete nginx.conf for the given set of running deployments.
    /// Uses per-model upstreams with path-prefix routing.
    /// </summary>
    internal static string GenerateConfig(IReadOnlyList<LlmDeploymentEntity> runningDeployments, int proxyPort)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by Claude Manager — {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("# Do not edit manually — changes will be overwritten on deployment changes.");
        sb.AppendLine();
        sb.AppendLine("events {");
        sb.AppendLine("    worker_connections 1024;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("http {");
        sb.AppendLine("    include /etc/nginx/mime.types;");
        sb.AppendLine("    default_type application/octet-stream;");
        sb.AppendLine("    sendfile on;");
        sb.AppendLine("    keepalive_timeout 65;");
        sb.AppendLine();

        if (runningDeployments.Count == 0)
        {
            // No running instances — return 503 for all requests
            sb.AppendLine($"    server {{");
            sb.AppendLine($"        listen {proxyPort};");
            sb.AppendLine($"        return 503 \"No vLLM instances are currently running.\";");
            sb.AppendLine($"    }}");
        }
        else
        {
            // Single upstream — round-robin across all running vLLM instances
            sb.AppendLine($"    upstream vllm_pool {{");
            foreach (var d in runningDeployments.OrderBy(d => d.HostPort))
                sb.AppendLine($"        server 127.0.0.1:{d.HostPort};");
            sb.AppendLine($"        keepalive 32;");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            sb.AppendLine($"    server {{");
            sb.AppendLine($"        listen {proxyPort};");
            sb.AppendLine($"        client_max_body_size 0;");
            sb.AppendLine();
            sb.AppendLine($"        location / {{");
            sb.AppendLine($"            proxy_pass http://vllm_pool;");
            sb.AppendLine($"            proxy_http_version 1.1;");
            sb.AppendLine($"            proxy_set_header Connection \"\";");
            sb.AppendLine($"            proxy_set_header Host $host;");
            sb.AppendLine($"            proxy_read_timeout 300s;");
            sb.AppendLine($"            proxy_connect_timeout 10s;");
            sb.AppendLine($"        }}");
            sb.AppendLine($"    }}");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Remote operations ─────────────────────────────────────────────────────

    /// <summary>
    /// Writes the generated nginx config to the host and starts or reloads the proxy container.
    /// Returns null on success, or an error message on failure.
    /// </summary>
    public async Task<string?> ApplyConfigAsync(
        GpuHostEntity host,
        IReadOnlyList<LlmDeploymentEntity> runningDeployments,
        CancellationToken ct = default)
    {
        if (host.ProxyPort is null)
            return "No proxy port configured for this host.";

        var config      = GenerateConfig(runningDeployments, host.ProxyPort.Value);
        var configB64   = Convert.ToBase64String(Encoding.UTF8.GetBytes(config));

        // One compound shell command: write config then start/reload container
        var cmd = BuildApplyCommand(configB64, host.SshUser);

        logger.LogInformation("Applying nginx proxy config on {Host} (port {Port}, {Count} deployments)",
            host.Host, host.ProxyPort, runningDeployments.Count);

        var (_, stderr, exitCode) = await ExecAsync(host, cmd, ct);

        if (exitCode != 0)
        {
            var error = stderr?.Trim() ?? "nginx apply command failed with no output.";
            logger.LogWarning("Nginx apply failed on {Host}: {Error}", host.Host, error);
            SetCache(host.HostId, NginxProxyStatus.Error, error);
            return error;
        }

        SetCache(host.HostId, NginxProxyStatus.Running, null);
        return null;
    }

    /// <summary>
    /// Queries the live status of the nginx proxy container on the host.
    /// </summary>
    public async Task<NginxProxyStatus> GetStatusAsync(
        GpuHostEntity host, CancellationToken ct = default)
    {
        var cmd = $"docker inspect -f '{{{{.State.Status}}}}' {ContainerName} 2>/dev/null || echo not_found";
        var (stdout, _, _) = await ExecAsync(host, cmd, ct);
        var status = ParseContainerStatus(stdout?.Trim());
        SetCache(host.HostId, status, null);
        return status;
    }

    /// <summary>
    /// Returns the nginx config file currently deployed on the host.
    /// </summary>
    public async Task<(string? Config, string? Error)> GetCurrentConfigAsync(
        GpuHostEntity host, CancellationToken ct = default)
    {
        var homeExpr = HomeExpr(host.SshUser);
        var cmd = $"cat \"{homeExpr}/{ConfigSubDir}/{ConfigFile}\" 2>/dev/null";
        var (stdout, stderr, exitCode) = await ExecAsync(host, cmd, ct);

        if (exitCode != 0 && !string.IsNullOrWhiteSpace(stderr))
            return (null, stderr.Trim());

        return (stdout ?? "", null);
    }

    /// <summary>
    /// Returns the cached status for a host without making a remote call.
    /// </summary>
    public (NginxProxyStatus Status, string? Error, DateTimeOffset UpdatedAt) GetCachedStatus(string hostId) =>
        _statusCache.TryGetValue(hostId, out var entry)
            ? entry
            : (NginxProxyStatus.Unknown, null, DateTimeOffset.MinValue);

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string BuildApplyCommand(string configBase64, string? sshUser)
    {
        // Resolve the SSH user's home directory explicitly via getent rather than relying on
        // $HOME or ~, both of which expand to /root when the command runs under sudo.
        // getent passwd always returns the correct entry regardless of execution context.
        var home = HomeExpr(sshUser);
        var dir  = $"{home}/{ConfigSubDir}";
        var path = $"{dir}/{ConfigFile}";

        var sb = new StringBuilder();
        sb.Append($"mkdir -p \"{dir}\"");
        sb.Append($" && echo {configBase64} | base64 -d > \"{path}\"");
        sb.Append($" && if docker inspect {ContainerName} > /dev/null 2>&1; then");
        sb.Append($"     if [ \"$(docker inspect -f '{{{{.State.Status}}}}' {ContainerName})\" = \"running\" ]; then");
        sb.Append($"         docker exec {ContainerName} nginx -s reload;");
        sb.Append($"     else");
        sb.Append($"         docker start {ContainerName};");
        sb.Append($"     fi;");
        sb.Append($" else");
        sb.Append($"     docker run -d --name {ContainerName} --network host --restart unless-stopped");
        sb.Append($"         -v \"{path}:/etc/nginx/nginx.conf:ro\"");
        sb.Append($"         nginx:alpine;");
        sb.Append($" fi");
        return sb.ToString();
    }

    /// <summary>
    /// Returns a shell expression that resolves to the SSH user's home directory.
    /// Uses getent passwd so it is correct even when the command runs under sudo
    /// (where $HOME and ~ expand to /root instead of the SSH user's home).
    /// Falls back to $HOME when no user is specified.
    /// </summary>
    private static string HomeExpr(string? sshUser) =>
        string.IsNullOrWhiteSpace(sshUser)
            ? "$HOME"
            : $"$(getent passwd {sshUser} | cut -d: -f6)";

    private static NginxProxyStatus ParseContainerStatus(string? raw) => raw switch
    {
        "running"                           => NginxProxyStatus.Running,
        "exited" or "created" or "paused"   => NginxProxyStatus.Stopped,
        "not_found" or null or ""           => NginxProxyStatus.NotFound,
        _                                   => NginxProxyStatus.Unknown,
    };

    private void SetCache(string hostId, NginxProxyStatus status, string? error) =>
        _statusCache[hostId] = (status, error, DateTimeOffset.UtcNow);

    private async Task<(string? Stdout, string? Stderr, int ExitCode)> ExecAsync(
        GpuHostEntity host, string command, CancellationToken ct)
    {
        var result = await executor.ExecuteShellAsync(
            new ShellCommand(command, host.RequiresSudo, host.SudoPassword),
            host.ToExecutionHost(),
            ct);
        return (result.Stdout, result.Stderr, result.ExitCode);
    }
}
